version: '3.9'
networks:
  common_network:
    driver: bridge
volumes:
  db_data:
    driver: local
services:
  db:
    container_name: db
    image: postgres:13-alpine
    networks:
      - common_network
    restart: always
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    container_name: app
    image: anhdau185/auth-service:latest
    networks:
      - common_network
    restart: always
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    links:
      - db
  dbadmin:
    container_name: dbadmin
    image: dpage/pgadmin4
    networks:
      - common_network
    restart: always
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_CONTAINER_PORT}'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
