services:
  db:
    image: postgres:13-alpine
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data
  web:
    image: anhdau185/auth-service:latest
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
